FROM java:8-jre
COPY producer_modbus-1.0-SNAPSHOT-jar-with-dependencies.jar /apps/deploy/
EXPOSE 8199
WORKDIR /apps/deploy/
CMD ["java", "-Xms128m", "-Xmx1500m",  "-Dfile.encoding=UTF-8", "-jar", "producer_modbus-1.0-SNAPSHOT-jar-with-dependencies.jar"]
